version: "3"

services:
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - mynetwork

  logger-service:
    build:
      context: ./../logger-service
      dockerfile: ./../logger-service/logger-service.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - mynetwork

  authentication:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=GMT connect_timeout=5"
    networks:
      - mynetwork

  postgres:
    build:
      context: ./../postgres
      dockerfile: ./../postgres/postgres.dockerfile
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db-data/postgres/:/private/var/lib/postgresql/data/
    networks:
      - mynetwork

  mongodb:
    build:
      context: ./../mongodb
      dockerfile: ./../mongodb/mongodb.dockerfile
    ports:
      - "27017:27017"
    volumes:
      - ./db-data/mongo/:/private/data/db
    networks:
      - mynetwork

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - mynetwork

  mail-service:
    build:
      context: ./../mail-service
      dockerfile: ./../mail-service/mail-service.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: none
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      FROM_NAME: "Tunaberk Almaci"
      FROM_ADDRESS: "tunaberk.almaci@example.com"
    networks:
      - mynetwork

networks:
  mynetwork: